# This script takes the bitstream generated by compile.tcl and program the fpga
source ./scripts/common.tcl

open_hw_manager
# localhost:3121 is the default
connect_hw_server 

current_hw_target [get_hw_targets */xilinx_tcf/Digilent/*]
open_hw_target

# set the first device to be current
set first_spartan7_device [lindex [get_hw_devices ${part_partnumber}*] 0]
current_hw_device ${first_spartan7_device}
refresh_hw_device -update_hw_probes false ${first_spartan7_device}

set_property PROGRAM.FILE ${cur_run_dir}/${proj_name}_${timestamp}.bit ${first_spartan7_device}
program_hw_devices ${first_spartan7_device}

exit